name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Fazer checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Conceder permissão de execução ao gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Configurar ambiente Android
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # Instalar dependências e compilar
      - name: Gradle Build
        run: ./gradlew build

      # Verificar código com Lint
      - name: Run Lint
        run: ./gradlew lint

      # Rodar testes unitários
      - name: Run Unit Tests
        run: ./gradlew test

      # Rodar testes de UI instrumentados (em emulador)
      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest

      # Construir o APK
      - name: Build APK
        run: ./gradlew assembleDebug
