name: Android CI

# Quando acionar o workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Fazer checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # Configurar ambiente Android
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # Instalar dependências
      - name: Gradle Build
        run: ./gradlew build

      # Verificar código com Lint
      - name: Run Lint
        run: ./gradlew lint

      # Rodar testes unitários
      - name: Run Unit Tests
        run: ./gradlew test

      # Rodar testes de UI instrumentados (em emulador)
      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest

      # Construir o APK (se necessário)
      - name: Build APK
        run: ./gradlew assembleDebug
